export const DEFAULT_PLACE = {
  name: "Bhilai",
  place_id: "bhilai",
  adm_area1: "Chhattisgarh",
  adm_area2: "Durg",
  country: "India",
  lat: "21.20919N",
  lon: "81.4285E",
  timezone: "Asia/Kolkata",
  type: "settlement",
  //   name: "Durg",
  //   place_id: "durg",
  //   adm_area1: "Chhattisgarh",
  //   adm_area2: "Durg",
  //   country: "India",
  //   lat: "21.19147N",
  //   lon: "81.27619E",
  //   timezone: "Asia/Kolkata",
  //   type: "settlement",
};
